language: android

jdk:
 - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

sudo: false

script: ./gradlew --stacktrace --debug build connectedCheck
