language: android

jdk:
 - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
